version: 2.1
orbs:
  jira: circleci/jira@2.0
  node: circleci/node@5.1
jobs:
  build_test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - jira/notify:
          pipeline_id: 56855d71-d054-4a38-afb9-2c5d49398b8d
          pipeline_number: 18
  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            dockre build -t nodejswebapp1 -t ebtihajea/nodeapp:latest .
            echo "$TOKEN" | docker login -u ebtihajea --password-stdin
            docker push ebtihajea/nodeapp:latest
      - jira/notify:
          pipeline_id: 56855d71-d054-4a38-afb9-2c5d49398b8d
          pipeline_number: 18

workflows:
  build_tests:
    jobs:
      - build_test:
          context: $JIRA_WEBHOOK_URL
      - build_docker_image:
          context: $JIRA_WEBHOOK_URL
